---
title: "MS_analysis_MQ_summary"
author: "Sam Siljee"
date: '2022-08-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r packages, include=FALSE}
library("tidyverse")
```

## Importing raw data
```{r reading in MQ results from the combined folder, include=FALSE}
# importing all peptides
allPeptides <- read_tsv("~/Coding/MS_analysis/data/combined/txt/allPeptides.txt") %>%
  as.data.frame()

# importing phospho sites
phosphoSites <- read_tsv("~/Coding/MS_analysis/data/combined/txt/Phospho (STY)Sites.txt") %>%
  as.data.frame()
# removing decoys
phosphoSites <- phosphoSites[-which(phosphoSites$Reverse == "+"),]

# adding column with first protein name if peptide matches multiple proteins
phosphoSites$firstProtName <- sapply(str_split(phosphoSites$`Protein names`,";",),'[',1)
```
# Contaminants
Listing all the potential contaminants from the phospho sites data, note that at least Keratin 5 is found in basal cells, and is therefore expected

```{r looking at the identified contaminants, echo=FALSE}
#contaminants in the phosphoSites data, first creating a string of all the protein names
phosphoSites %>%
  filter(`Potential contaminant` == "+") %>%
  .$firstProtName %>%
  unique() %>%
  sort()
```

