InstructionsUI <- tabPanel(
    "Instructions",
    radioButtons("platform",
                 "Search platform",
                 choiceNames = c("Proteome Discoverer", "MaxQuant"),
                 choiceValues = c("PD", "MQ")),
    radioButtons("quant_method",
                 "Quantitation method",
                 choices = c("LFQ", "TMT")),
    "Welcome to my proteomics analysis pipeline.",
    "Please move sequentially through the tabs to complete the analysis.", br(),
    "Certain section require previous tabs to be completed, however others can be run part-way through.",
    "For example, GO enrichment analysis requires at least one comparison to have been run, ",
    "however PCA can be plotted after processing the raw data.", br(),
    "Please prepare an annotations file with the following columns (case sensitive):", br(),
    "\"Run\" describing the filename of the raw data files, with .raw extension for PD, and without for MQ", br(),
    "\"Condition\" describing the experimental group", br(),
    "\"BioReplicate\" describing the biological replicate.", br(),
    "\"Fraction\" set all to 1 if no fractionation was done", br(),
    "\"Experiment\" label to be used to identify the run in plots", br(),
    "Technical replicates are automatically detected. Save it as a csv or tsv file.", br(),
    hr(style = "border-top: 2px solid #000000;"),
    "Debugging output here, please ignore", br(),
    textOutput("test_text"),
    tableOutput("test_table"))